<a href="https://colab.research.google.com/github/moni8210/Assignment-3/blob/main/nlp_with_deeplearning_v_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample data
texts = ["I love machine learning", "Deep learning is amazing"]

# Tokenization: Convert words to numbers
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

# Padding: Make sequences the same length
padded_sequences = pad_sequences(sequences, padding='post')

print(padded_sequences)

[[2 3 4 1]
 [5 1 6 7]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Define the model
model = Sequential()
model.add(Embedding(input_dim=1000, output_dim=64))
model.add(LSTM(64))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 64)          64000     
                                                                 
 lstm (LSTM)                 (None, 64)                33024     
                                                                 
 dense (Dense)               (None, 1)                 65        
                                                                 
Total params: 97089 (379.25 KB)
Trainable params: 97089 (379.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Assume X_train, y_train, X_val, y_val are defined
# Assume X_train, y_train, X_val, y_val are defined
import numpy as np
y_train = np.array(y_train) # Convert y_train to a NumPy array
y_val = np.array(y_val) # Convert y_val to a NumPy array

model.fit(X_train, y_train, epochs=5, validation_data=(X_val, y_val))




Epoch 1/5
1/1 [==============================] - 3s 3s/step - loss: 0.6931 - accuracy: 0.6667 - val_loss: 0.6937 - val_accuracy: 0.0000e+00
Epoch 2/5
1/1 [==============================] - 0s 37ms/step - loss: 0.6882 - accuracy: 0.6667 - val_loss: 0.6963 - val_accuracy: 0.0000e+00
Epoch 3/5
1/1 [==============================] - 0s 41ms/step - loss: 0.6832 - accuracy: 0.6667 - val_loss: 0.6988 - val_accuracy: 0.0000e+00
Epoch 4/5
1/1 [==============================] - 0s 38ms/step - loss: 0.6782 - accuracy: 0.6667 - val_loss: 0.7015 - val_accuracy: 0.0000e+00
Epoch 5/5
1/1 [==============================] - 0s 38ms/step - loss: 0.6731 - accuracy: 0.6667 - val_loss: 0.7043 - val_accuracy: 0.0000e+00


In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_val, y_val)
print(f'Validation Accuracy: {accuracy}')


1/1 [==============================] - 0s 25ms/step - loss: 0.7043 - accuracy: 0.0000e+00
Validation Accuracy: 0.0


In [ ]:
# Make predictions on the old text data
predictions = model.predict(padded_sequences)
print(predictions)


1/1 [==============================] - 0s 424ms/step
[[0.49574393]
 [0.49447405]
 [0.47986504]
 [0.47686788]]


In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp("Natural language processing with spaCy is easy!")
for token in doc:
    print(token.text, token.pos_)


Natural ADJ
language NOUN
processing NOUN
with ADP
spaCy PROPN
is AUX
easy ADJ
! PUNCT


In [ ]:
from sklearn.datasets import fetch_20newsgroups

# Load the dataset
newsgroups_train = fetch_20newsgroups(subset='train')
print(newsgroups_train.data[:2])  # Print the first two posts


["From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n", "From: guykuo@carson.u.washington.edu (Guy Kuo)\nSubject: SI Clock Poll - Final Call\nSummary: Final call for SI clock reports\nKeywords: SI,acceleration,clock,upgrade\nArticle-I.D.: shelley.1qvfo9INNc3s\nOrganization: University of Washington\nLines: 1